### PR TITLE
Added Tkinter GUI

### PR DESCRIPTION
**Pull request by arpitmisraw**

### CODE REVIEW

**Comment by arpitmisraw** [comment]
@mrsaicharan1  I've added the GUI using Tkinter.

Issue - #5

**Comment by mrsaicharan1** [comment]
Is the application working properly? I had encountered some exceptions while testing it out.
@arpitmisraw

**Comment by arpitmisraw** [comment]
I'll see to it. Can you give me the time till tomorrow?

**Comment by arpitmisraw** [comment]
Also, can you please tell me the problems you are facing?

**Comment by Anupam-dagar** [comment]
@mrsaicharan1 please give a detailed description of the problems so that they can be resolved, some problems is difficult to understand.

**Pull request closed without merging**
