### PR TITLE
Added the Tkinter GUI and word auto-correct

### PR DESCRIPTION
**Pull request by arpitmisraw**
@mrsaicharan1  I've sent you the pull request.

Tkinter should be installed to use it. I can update the readme once you merge it.
I've tested it in two computers, and it seems to work.

Issues solved - #5  and #30

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
@arpitmisraw  Just create a GUI branch for your code and merge it. I'll check it on the branch.

**Comment by arpitmisraw** [comment]
Okay.

**Comment by arpitmisraw** [comment]
I created it. Should I send a pull request too, or you'll check it in my branch?

**Comment by mrsaicharan1** [comment]
@arpitmisraw  I'll check it on the branch

**Comment by mrsaicharan1** [comment]
@arpitmisraw Fork and branch. I need to review the code and analyze.

**Comment by arpitmisraw** [comment]
Okay. I'll keep the code in the GUI branch of my fork. Tell me when you need me to put a PR.

**Comment by mrsaicharan1** [comment]
@arpitmisraw  Has some conflicts due to other merges . Please do a few changes and send PR.

**Pull request closed without merging**
